### ISSUE TITLE
JSON parsing may throw error if payload is too short

### ISSUE THREAD

**Issue by vcharpenay** [Hypermedea/hypermedea#43]
```
[h] [HttpOperation] Method: GET, Target: https://ci.mines-stetienne.fr/simu/storageRack/properties/conveyorSpeed, Payload: <none>
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at cartago.ArtifactOpMethod.exec(ArtifactOpMethod.java:39)
	at cartago.Artifact.doOperation(Artifact.java:447)
	at cartago.Artifact$ArtifactAdapter.doOperation(Artifact.java:1343)
	at cartago.Workspace.serveOperation(Workspace.java:1579)
	at cartago.Workspace$EnvironmentController.run(Workspace.java:1922)
Caused by: javax.json.JsonException: Cannot auto-detect encoding, not enough chars
	at org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:130)
	at org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:75)
	at org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:95)
	at org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:73)
	at org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:136)
	at javax.json.Json.createReader(Json.java:225)
	at org.hypermedea.ct.json.JsonHandler.deserialize(JsonHandler.java:58)
	at org.hypermedea.ct.RepresentationHandlers.deserialize(RepresentationHandlers.java:36)
	at org.hypermedea.op.http.HttpResponse.getPayload(HttpResponse.java:64)
	at org.hypermedea.op.BaseResponse.toString(BaseResponse.java:26)
	at org.hypermedea.HypermedeaArtifact.initiateOperation(HypermedeaArtifact.java:479)
	at org.hypermedea.HypermedeaArtifact.get(HypermedeaArtifact.java:175)
	... 9 more
```

(returned value is `0`)

**Comment by vcharpenay** [comment]
c346ebf
